version: '3.8'
services:
  api:
    restart: unless-stopped
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app_network

  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./Docker/nginx:/etc/nginx/conf.d
    networks:
      - app_network

networks:
  app_network: