name = "api-multi-oauth2-react-native"
main = "src/index.ts"
compatibility_date = "2023-04-23"
usage_model = "bundled"
node_compat = false

[triggers]
crons = [ ]

[vars]
NAME = "API for Multi OAuth 2 with React Native"
VERSION = "1.0.0"
# MYSQL_HOST = "localhost"
# MYSQL_USER = "root"
# MYSQL_PASS = ""
# MYSQL_BASE = "multi_oauth2_react_native"