name: Deploy to Cloudflare Workers

on:
  create:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          SECRETS: MYSQL_HOST MYSQL_USER MYSQL_PASS MYSQL_BASE
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
          MYSQL_BASE: ${{ secrets.MYSQL_BASE }}